### ISSUE TITLE
HomeFragment.java line 10

### ISSUE THREAD

**Issue by aiyu-ayaan** [BIT-Lalpur-App/BIT-App#103]

**Comment by aiyu-ayaan** [comment]
```kotlin

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View android.view.MenuItem.getActionView()' on a null object reference
       at com.atech.bit.ui.fragments.home.HomeFragment$createMenu$1$1.run(HomeFragment.java:10)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8184)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```
